spring:
  application:
    name: rancher-web
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      encoding: utf-8
      suffix: .html
      servlet:
        content-type: text/html

server:
  port: 11911


route add 42.192.204.211 10.0.16.12
